[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd backend",
  "pip install --user fastapi uvicorn anthropic python-dotenv pydantic"
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT" 