[phases.setup]
nixPkgs = [
  "python311", 
  "python311Packages.fastapi", 
  "python311Packages.uvicorn", 
  "python311Packages.anthropic", 
  "python311Packages.python-dotenv", 
  "python311Packages.pydantic"
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT" 