[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd backend",
  "python -m pip install --user fastapi uvicorn anthropic python-dotenv pydantic"
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT" 